### ISSUE TITLE
opencv-python==4.2.0.34 no longer on registry (macOS)

### ISSUE THREAD

**Issue by mattmischuk** [vasani-arpit/image-qr-code-scanner#1]
### Bug Description
Instructions in `README.md` are not up-to-date, regarding `opencv-python==4.2.0.34`.

### Reproduction Steps
1. Type command `pip3 install opencv-python==4.2.0.34`
2. Returns error (see "Screenshots & Errors" section)

### Expected Behavior
The python module being pasted from docs is accurate to the available versions found on the registry. 

### Screenshots & Errors

```bash
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.34 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66)
ERROR: No matching distribution found for opencv-python==4.2.0.34
```

As a result of the missing dependency (node error): 

```bash
Traceback (most recent call last):
  File "/@workspace/node_modules/image-qr-code-scanner/scanner.py", line 1, in <module>
    from pyzbar.pyzbar import decode
ModuleNotFoundError: No module named 'pyzbar'
```

**Desktop (please complete the following information):**
	- OS: macOS
	- OS Version: 12.4
	- Browser: n/a
 	- pip3 Version: `pip 22.3.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`

**Smartphone (please complete the following information):**
	- n/a

**Comment by vasani-arpit** [comment]
Thanks for reporting. Will look into it.

**Comment by vasani-arpit** [comment]
Updated requirements please try and let me know if error still persists. https://github.com/vasani-arpit/image-qr-code-scanner/commit/0b2b76951b7737ee9fdcbc12cacce176443f1ed4#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15

**Comment by mattmischuk** [comment]
@vasani-arpit  acknowledged, however, I won't be able to test until next week.

**Comment by vasani-arpit** [comment]
No rush. I don't have a mac so I am relying on you to verify.

**Comment by eventplushki** [comment]
Hi! After the comfyUI update on 22/01/2025, the qr scanner nodes are not working. Is there anything I can do to make it work again?

**Comment by vasani-arpit** [comment]
What is the issue here? is it a version conflict in dependencies?

**Comment by eventplushki** [comment]
> What is the issue here? is it a version conflict in dependencies?

In cmd "0.0 seconds (IMPORT FAILED): D:\sd\ComfyUI\ComfyUI\custom_nodes\ComfyQR-scanning-nodes" where i can debug this?

**Comment by eventplushki** [comment]
When i try to reinstall this: "Installation Error:
ComfyQR-scanning-nodes install failed: Failed to clone repo: https://github.com/coreyryanhanson/ComfyQR-scanning-nodes"

**Comment by vasani-arpit** [comment]
You are reporting this error to wrong repo owner. 

if cloning is the issue then it's github's fault or some network error. The error message might be incorrect, in that case please tale a look at other similar issue raised [here](https://github.com/coreyryanhanson/ComfyQR-scanning-nodes/issues).

**Comment by eventplushki** [comment]
I choose not last version and get error after reinstall:

Traceback (most recent call last):
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\zbar_library.py", line 50, in load_objects
    deps = [
           ^
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\zbar_library.py", line 51, in <listcomp>
    cdll.LoadLibrary(str(directory.joinpath(dep)))
  File "ctypes\__init__.py", line 454, in LoadLibrary
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd\ComfyUI\ComfyUI\nodes.py", line 2108, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\ComfyUI\ComfyUI\custom_nodes\comfyqr-scanning-nodes\__init__.py", line 1, in <module>
    from .qr_validation import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\sd\ComfyUI\ComfyUI\custom_nodes\comfyqr-scanning-nodes\qr_validation.py", line 3, in <module>
    from pyzbar.pyzbar import decode
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
                   ^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
                             ^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
                            ^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\zbar_library.py", line 54, in load_objects
    libzbar = cdll.LoadLibrary(str(directory.joinpath(fname)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ctypes\__init__.py", line 454, in LoadLibrary
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'D:\sd\ComfyUI\python_embeded\Lib\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by eventplushki** [comment]
I reinstall Visual C++ Redistributable Packages for Visual Studio 2013 vcredist_x64.exe and it`s fixed problem
